# frozen_string_literal: true

require "ffi"

module ZXingFFI
  # FFI declarations for the zxing-cpp C API (ZXingC.h, verified against 3.1.1).
  #
  # This module knows nothing about Ruby-level types: it only declares functions, enums and structs.
  # {Reader} owns every native object's lifetime. The library is loaded lazily by {.load!}.
  #
  # Ownership (from the header): non-const +ZXing_X*+ results are freed with +ZXing_X_delete+; non-const
  # +char*+/+uint8_t*+ results with +ZXing_free+; const results belong to their parent.
  module Native
    extend FFI::Library

    # ZXing_ImageFormat (explicit values in the header).
    enum :image_format, [
      :none, 0,
      :lum, 0x01000000,
      :lum_a, 0x02000000,
      :rgb, 0x03000102,
      :bgr, 0x03020100,
      :rgba, 0x04000102,
      :argb, 0x04010203,
      :bgra, 0x04020100,
      :abgr, 0x04030201
    ]
    enum :binarizer, [:local_average, 0, :global_histogram, :fixed_threshold, :bool_cast]
    enum :ean_add_on_symbol, [:ignore, 0, :read, :require]
    enum :text_mode, [:plain, 0, :eci, :hri, :escaped, :hex, :hex_eci]
    enum :content_type, [:text, 0, :binary, :mixed, :gs1, :iso15434, :unknown_eci]
    enum :error_type, [:none, 0, :format, :checksum, :unsupported]

    # ZXing_BarcodeFormat values are generated by macros and changed in 3.0: never hardcode them.
    # They are plain C enum values, i.e. ints; see {Formats} for the runtime map.
    typedef :int, :barcode_format

    # ZXing_PointI
    class PointI < FFI::Struct
      layout :x, :int, :y, :int
    end

    # ZXing_Position
    class Position < FFI::Struct
      layout :top_left, PointI, :top_right, PointI, :bottom_right, PointI, :bottom_left, PointI
    end

    # [name, args, return, options] of functions every supported library exports.
    REQUIRED_FUNCTIONS = [
      [:ZXing_Version, [], :string],
      [:ZXing_free, [:pointer], :void],
      [:ZXing_LastErrorMsg, [], :pointer],

      [:ZXing_ImageView_new, [:pointer, :int, :int, :image_format, :int, :int], :pointer],
      [:ZXing_ImageView_delete, [:pointer], :void],
      [:ZXing_ImageView_crop, [:pointer, :int, :int, :int, :int], :void],
      [:ZXing_ImageView_rotate, [:pointer, :int], :void],

      [:ZXing_BarcodeFormatSymbology, [:barcode_format], :barcode_format],
      [:ZXing_BarcodeFormatFromString, [:string], :barcode_format],
      [:ZXing_BarcodeFormatToString, [:barcode_format], :pointer],
      [:ZXing_BarcodeFormatsList, [:barcode_format, :pointer], :pointer],
      [:ZXing_BarcodeFormatsFromString, [:string, :pointer], :pointer],
      [:ZXing_BarcodeFormatsToString, [:pointer, :int], :pointer],

      [:ZXing_Barcode_isValid, [:pointer], :bool],
      [:ZXing_Barcode_errorType, [:pointer], :error_type],
      [:ZXing_Barcode_errorMsg, [:pointer], :pointer],
      [:ZXing_Barcode_format, [:pointer], :barcode_format],
      [:ZXing_Barcode_symbology, [:pointer], :barcode_format],
      [:ZXing_Barcode_contentType, [:pointer], :content_type],
      [:ZXing_Barcode_bytes, [:pointer, :pointer], :pointer],
      [:ZXing_Barcode_bytesECI, [:pointer, :pointer], :pointer],
      [:ZXing_Barcode_text, [:pointer], :pointer],
      [:ZXing_Barcode_symbologyIdentifier, [:pointer], :pointer],
      [:ZXing_Barcode_position, [:pointer], Position.by_value],
      [:ZXing_Barcode_orientation, [:pointer], :int],
      [:ZXing_Barcode_hasECI, [:pointer], :bool],
      [:ZXing_Barcode_isInverted, [:pointer], :bool],
      [:ZXing_Barcode_isMirrored, [:pointer], :bool],
      [:ZXing_Barcode_lineCount, [:pointer], :int],
      [:ZXing_Barcode_sequenceIndex, [:pointer], :int],
      [:ZXing_Barcode_sequenceSize, [:pointer], :int],
      [:ZXing_Barcode_sequenceId, [:pointer], :pointer],
      [:ZXing_Barcode_extra, [:pointer, :string], :pointer],

      [:ZXing_Barcodes_delete, [:pointer], :void],
      [:ZXing_Barcodes_size, [:pointer], :int],
      [:ZXing_Barcodes_at, [:pointer, :int], :pointer],

      [:ZXing_ReaderOptions_new, [], :pointer],
      [:ZXing_ReaderOptions_delete, [:pointer], :void],
      [:ZXing_ReaderOptions_setTryHarder, [:pointer, :bool], :void],
      [:ZXing_ReaderOptions_setTryRotate, [:pointer, :bool], :void],
      [:ZXing_ReaderOptions_setTryInvert, [:pointer, :bool], :void],
      [:ZXing_ReaderOptions_setTryDownscale, [:pointer, :bool], :void],
      [:ZXing_ReaderOptions_setIsPure, [:pointer, :bool], :void],
      [:ZXing_ReaderOptions_setValidateOptionalChecksum, [:pointer, :bool], :void],
      [:ZXing_ReaderOptions_setReturnErrors, [:pointer, :bool], :void],
      [:ZXing_ReaderOptions_setFormats, [:pointer, :pointer, :int], :void],
      [:ZXing_ReaderOptions_setBinarizer, [:pointer, :binarizer], :void],
      [:ZXing_ReaderOptions_setEanAddOnSymbol, [:pointer, :ean_add_on_symbol], :void],
      [:ZXing_ReaderOptions_setTextMode, [:pointer, :text_mode], :void],
      [:ZXing_ReaderOptions_setMinLineCount, [:pointer, :int], :void],
      [:ZXing_ReaderOptions_setMaxNumberOfSymbols, [:pointer, :int], :void],
      [:ZXing_ReaderOptions_getTryHarder, [:pointer], :bool],
      [:ZXing_ReaderOptions_getTryRotate, [:pointer], :bool],
      [:ZXing_ReaderOptions_getTryInvert, [:pointer], :bool],
      [:ZXing_ReaderOptions_getTryDownscale, [:pointer], :bool],
      [:ZXing_ReaderOptions_getIsPure, [:pointer], :bool],
      [:ZXing_ReaderOptions_getValidateOptionalChecksum, [:pointer], :bool],
      [:ZXing_ReaderOptions_getReturnErrors, [:pointer], :bool],
      [:ZXing_ReaderOptions_getFormats, [:pointer, :pointer], :pointer],
      [:ZXing_ReaderOptions_getBinarizer, [:pointer], :binarizer],
      [:ZXing_ReaderOptions_getEanAddOnSymbol, [:pointer], :ean_add_on_symbol],
      [:ZXing_ReaderOptions_getTextMode, [:pointer], :text_mode],
      [:ZXing_ReaderOptions_getMinLineCount, [:pointer], :int],
      [:ZXing_ReaderOptions_getMaxNumberOfSymbols, [:pointer], :int],

      # Releases the GVL so several threads decode concurrently.
      [:ZXing_ReadBarcodes, [:pointer, :pointer], :pointer, {blocking: true}]
    ].freeze

    # Optional features: feature name => [[name, args, return], ...]; all functions must resolve.
    OPTIONAL_FUNCTIONS = {
      # only with ZXING_EXPERIMENTAL_API
      try_denoise: [
        [:ZXing_ReaderOptions_setTryDenoise, [:pointer, :bool], :void],
        [:ZXing_ReaderOptions_getTryDenoise, [:pointer], :bool]
      ],
      # newer name of ZXing_Barcode_orientation
      rotation: [[:ZXing_Barcode_rotation, [:pointer], :int]],
      # bounds-checked ImageView constructor
      image_view_new_checked: [
        [:ZXing_ImageView_new_checked, [:pointer, :int, :int, :int, :image_format, :int, :int], :pointer]
      ]
    }.freeze

    @mutex = Mutex.new
    @library = nil
    @features = {}.freeze

    class << self
      # Loads and attaches libZXing once (thread safe). Later calls are no-ops.
      #
      # @return [LibraryLoader::Found]
      # @raise [LibraryNotFound, IncompatibleLibrary]
      def load!
        return @library if @library

        @mutex.synchronize do
          return @library if @library

          found = LibraryLoader.find
          ffi_lib(found.path)
          REQUIRED_FUNCTIONS.each { |name, args, ret, opts| attach_function(name, args, ret, **(opts || {})) }
          @features = OPTIONAL_FUNCTIONS.to_h { |feature, functions| [feature, attach_optional(functions)] }.freeze
          @library = found
        end
      end

      # @return [Boolean] whether {.load!} has succeeded
      def loaded?
        !@library.nil?
      end

      # @return [LibraryLoader::Found, nil]
      attr_reader :library

      # Whether an optional native feature is present: +:try_denoise+, +:rotation+, +:image_view_new_checked+.
      # @return [Boolean]
      def supports?(feature)
        load!
        @features.fetch(feature.to_sym) { raise ArgumentError, "unknown native feature: #{feature.inspect}" }
      end

      # @return [Array<Symbol>] optional features present in the loaded library
      def optional_features
        load!
        @features.select { |_, present| present }.keys
      end

      # Rotation of a barcode in degrees as reported by the library (-180..180).
      def barcode_rotation(barcode)
        @features[:rotation] ? ZXing_Barcode_rotation(barcode) : ZXing_Barcode_orientation(barcode)
      end

      # Copies a caller-owned C string into a UTF-8 Ruby String and frees it. NULL → nil.
      def take_string(pointer)
        return nil if pointer.nil? || pointer.null?

        pointer.read_string.force_encoding(Encoding::UTF_8)
      ensure
        ZXing_free(pointer) if pointer && !pointer.null?
      end

      # Calls the block with an +int*+ out-parameter, copies the returned caller-owned
      # buffer of that many bytes into a BINARY String and frees it.
      def take_bytes
        length = FFI::MemoryPointer.new(:int)
        pointer = yield length
        return "".b if pointer.nil? || pointer.null?

        pointer.read_bytes(length.read_int)
      ensure
        ZXing_free(pointer) if pointer && !pointer.null?
      end

      # Like {.take_bytes} for caller-owned +ZXing_BarcodeFormat*+ arrays.
      # @return [Array<Integer>, nil] nil when the library returned NULL
      def take_formats
        count = FFI::MemoryPointer.new(:int)
        pointer = yield count
        return nil if pointer.nil? || pointer.null?

        pointer.read_array_of_int(count.read_int)
      ensure
        ZXing_free(pointer) if pointer && !pointer.null?
      end

      # Fetches (and clears) the calling thread's last error message.
      # @return [String, nil]
      def last_error_message
        take_string(ZXing_LastErrorMsg())
      end

      private

      def attach_optional(functions)
        functions.each { |name, args, ret| attach_function(name, args, ret) }
        true
      rescue FFI::NotFoundError
        false
      end
    end
  end
end
