# frozen_string_literal: true

require "test_helper"
require "yaml"

# Every symbology decodes from a clean PGM made by an independent encoder
# (test/fixtures/symbologies, generated by script/fixtures/symbologies.rb).
class SymbologiesTest < Minitest::Test
  INDEX = File.join(ZXingFFI::TestSupport::FIXTURES, "symbologies", "index.yml")
  ENTRIES = File.exist?(INDEX) ? YAML.safe_load_file(INDEX, aliases: true) : []

  def setup
    require_native!
    skip "symbology fixtures missing (script/generate_fixtures symbologies)" if ENTRIES.empty?
  end

  ENTRIES.each do |entry|
    name = File.basename(entry.fetch("file"), ".pgm")

    define_method(:"test_decodes_#{name}") do
      barcodes = ZXingFFI.read(load_image(entry), **read_options(entry))

      assert_equal 1, barcodes.size, "#{name}: #{barcodes.map(&:text).inspect}"
      barcode = barcodes.first
      assert_equal entry.fetch("format").to_sym, barcode.format, name
      assert_equal entry.fetch("symbology").to_sym, barcode.symbology, name
      assert_equal entry.fetch("text"), barcode.text, name
      assert_equal expected_bytes(entry), barcode.bytes, name
      assert_equal entry["content_type"].to_sym, barcode.content_type, name if entry["content_type"]
      assert barcode.valid?, name
      assert_nil barcode.error
      assert_equal Encoding::UTF_8, barcode.text.encoding
      assert barcode.text.valid_encoding?
      expected_sequence(entry).then { |seq| seq ? assert_equal(seq, barcode.sequence, name) : assert_nil(barcode.sequence, name) }
      assert_equal ZXingFFI::Formats.name_for(ZXingFFI::Formats.value_for(barcode.format)), barcode.format_name
      refute_empty barcode.symbology_identifier
    end
  end

  def test_every_readable_symbology_family_is_covered
    covered = ENTRIES.map { |e| e.fetch("symbology").to_sym }.uniq
    families = ZXingFFI.formats.map { |f| ZXingFFI::Formats.symbol_for(ZXingFFI::Formats.table.by_symbol.fetch(f).symbology) }.uniq
    missing = families - covered - %i[other_barcode] # no encoder exists for the generic "Other barcode"

    assert_empty missing, "readable symbology families without a clean fixture"
  end

  def test_inverted_and_mirrored_flags
    assert decode("qr_code_inverted").inverted?
    refute decode("qr_code").inverted?
    assert decode("qr_code_mirrored").mirrored?
    refute decode("qr_code").mirrored?
  end

  def test_binary_payload_text_is_not_truncated_at_nul
    barcode = decode("qr_code_binary")

    assert_equal :binary, barcode.content_type
    assert_equal "BIN\x00\x01\x7F\x80".b + "\xFE\xFF".b, barcode.bytes
    assert_equal "BIN\u0000\u0001\u007F\u0080þÿ", barcode.text
    assert_equal "base64", barcode.to_h[:bytes_encoding]
  end

  def test_utf8_text
    barcode = decode("qr_code_utf8")
    assert_equal "Grüße, 世界", barcode.text
    assert_equal "Grüße, 世界".b, barcode.bytes
  end

  def test_structured_append
    first = decode("qr_code_structured_append_1")
    second = decode("qr_code_structured_append_2")

    assert_equal [0, 2], first.sequence.values_at(:index, :size)
    assert_equal [1, 2], second.sequence.values_at(:index, :size)
    assert_equal first.sequence[:id], second.sequence[:id]
  end

  def test_gs1_content
    barcode = decode("data_matrix_gs1")
    assert_equal :gs1, barcode.content_type
    assert_includes barcode.text, "\x1D"
    hri = ZXingFFI.read(load_image(entry_for("data_matrix_gs1")), text_mode: :hri).first.text
    %w[(01)09501101530003 (17)140704 (10)AB-123].each { |field| assert_includes hri, field }
  end

  def test_checksum_validation_default_drops_codes_without_check_digit
    %w[code_39_no_check itf_no_check].each do |name|
      image = load_image(entry_for(name))
      assert_empty ZXingFFI.read(image), "#{name} must be dropped with validate_optional_checksum: true"
      assert_equal 1, ZXingFFI.read(image, validate_optional_checksum: false).size, name
    end
  end

  def test_return_errors_reports_the_checksum_error
    barcodes = ZXingFFI.read(load_image(entry_for("code_39_no_check")), return_errors: true)

    assert_equal 1, barcodes.size
    barcode = barcodes.first
    refute barcode.valid?
    assert_equal :checksum, barcode.error[:type]
    refute_empty barcode.error[:message].to_s
  end

  def test_ean_add_on_modes
    image = load_image(entry_for("ean_13_add_on_5"))
    ignored = ZXingFFI.read(image, ean_add_on: :ignore).first
    read = ZXingFFI.read(image, ean_add_on: :read).first

    assert_equal 13, ignored.text.length
    assert_operator read.text.length, :>, 13
    assert_empty ZXingFFI.read(load_image(entry_for("ean_13")), ean_add_on: :require)
  end

  def test_symbology_identifiers
    assert_equal "]Q1", decode("qr_code").symbology_identifier
    assert_match(/\A\]C\d\z/, decode("code_128").symbology_identifier)
    assert_match(/\A\]d\d\z/, decode("data_matrix").symbology_identifier)
    assert_match(/\A\]E\d\z/, decode("ean_13").symbology_identifier)
  end

  private

  def entry_for(name)
    ENTRIES.find { |e| File.basename(e["file"], ".pgm") == name } or skip("no fixture #{name}")
  end

  def decode(name)
    entry = entry_for(name)
    ZXingFFI.read(load_image(entry), **read_options(entry)).first or flunk("#{name} did not decode")
  end

  def load_image(entry)
    ZXingFFI::Image.from_pgm(File.binread(fixture_path(entry.fetch("file"))))
  end

  def read_options(entry)
    (entry["read_options"] || {}).to_h do |key, value|
      [key.to_sym, value.is_a?(String) ? value.to_sym : value]
    end
  end

  def expected_bytes(entry)
    entry["bytes_hex"] ? [entry["bytes_hex"]].pack("H*") : entry.fetch("text").b
  end

  def expected_sequence(entry)
    sequence = entry["sequence"] or return nil
    sequence.transform_keys(&:to_sym)
  end
end
