#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the symbology fixtures for the native tests: one clean 8-bit binary PGM (P5, maxval 255,
# black on white, generous quiet zone, 3-4 px modules, no rotation) per readable symbology/variant in
# test/fixtures/symbologies/, plus test/fixtures/symbologies/index.yml with the expected results (schema:
# test/fixtures/README.md). These are not corpus fixtures, so no manifest.d fragment is written.
#
#   mise exec -- bundle exec ruby script/fixtures/symbologies.rb
#   mise exec -- bundle exec script/generate_fixtures symbologies
#
# Encoders are independent of zxing-cpp so the tests are not circular: zint (>= 2.16) for most symbologies and
# the rqrcode gem for QR Code. zint's PNG output is converted to grayscale with ImageMagick 7 (`magick`). The output is
# deterministic: re-running with the same tool versions produces identical bytes.

require "fileutils"
require "open3"
require "yaml"

begin
  require "rqrcode"
rescue LoadError
  abort "symbologies: the rqrcode gem is missing; run via `mise exec -- bundle exec` (Gemfile group :fixtures)"
end

module SymbologyFixtures
  ROOT = File.expand_path("../..", __dir__)
  OUT_DIR = File.join(ROOT, "test", "fixtures", "symbologies")
  INDEX = File.join(OUT_DIR, "index.yml")
  MIN_ZINT = Gem::Version.new("2.16.0")

  WHITE = 255
  BLACK = 0
  BILEVEL = [BLACK, WHITE].pack("C*").freeze

  # zint options. For raster output --scale=1 means 2 px per module; --whitesp/--vwhitesp add to --quietzones.
  COMMON = %w[--notext --quietzones].freeze
  LINEAR = %w[--scale=1.5 --whitesp=5 --vwhitesp=5].freeze # 3 px modules, standard quiet zone + 5 modules
  BARS = [*LINEAR, "--height=20"].freeze # shorter bars (default is 50+ modules) keep the files small
  ADDON_BARS = [*LINEAR, "--height=30"].freeze # ~8 modules are cropped off by :align_addon
  MATRIX = %w[--scale=2 --whitesp=4 --vwhitesp=4].freeze # 4 px modules, standard quiet zone + 4 modules
  QR_ZINT = %w[--scale=2].freeze # 4 px modules, standard 4-module quiet zone (like the rqrcode fixtures)
  MARGIN_PX = 15 # white margin outside zint's ITF-14 bearer box (zint puts the whitespace inside the box)

  # rqrcode fixtures: byte mode, EC level M, 4 px modules, 4-module quiet zone.
  QR_MODULE_PX = 4
  QR_QUIET_ZONE = 4

  # GS1 element string: the variable-length AI 10 precedes AI 17, so the plain text contains one GS (0x1D) separator.
  GS1_AIS = "[01]09501101530003[10]AB-123[17]140704"
  GS1_TEXT = "010950110153000310AB-123\x1D17140704"
  GTIN = "0950110153000" # DataBar: zint adds the check digit; zxing-cpp reports "01" + GTIN-14
  GTIN_TEXT = "0109501101530003"
  BINARY = "BIN".b + [0x00, 0x01, 0x7F, 0x80, 0xFE, 0xFF].pack("C*")

  # Symbology family (Barcode#symbology) of every format used below.
  FAMILY = {
    "qr_code" => "qr_code", "micro_qr_code" => "qr_code", "rmqr_code" => "qr_code",
    "data_matrix" => "data_matrix", "aztec" => "aztec", "maxicode" => "maxicode",
    "pdf417" => "pdf417", "micropdf417" => "pdf417",
    "code_128" => "code_128", "code_93" => "code_93", "codabar" => "codabar", "itf" => "itf",
    "code_39" => "code_39", "code_39_extended" => "code_39", "code_32" => "code_39", "pharmazentralnummer" => "code_39",
    "ean_13" => "ean_upc", "ean_8" => "ean_upc", "upc_e" => "ean_upc",
    "databar_omni" => "databar", "databar_stacked" => "databar", "databar_limited" => "databar",
    "databar_expanded" => "databar", "databar_expanded_stacked" => "databar",
    "telepen_alpha" => "telepen", "telepen_numeric" => "telepen", "dx_film_edge" => "other_barcode"
  }.freeze

  TRANSFORMS = {
    invert: "inverted: white on black",
    mirror: "mirrored horizontally",
    align_addon: "rows above the add-on bars removed",
    margin: "#{MARGIN_PX} px white margin added around the bearer box"
  }.freeze

  HEADER = <<~YAML
    # GENERATED by script/fixtures/symbologies.rb - do not edit. Regenerate with
    #   mise exec -- bundle exec script/generate_fixtures symbologies
    # Schema: test/fixtures/README.md. Encoders (independent of zxing-cpp): %<encoders>s.
    #
    # Expectations: what zxing-cpp 3.1.1 reports for ZXingFFI.read(image, **read_options) with the gem defaults
    # (text_mode: :plain, formats: :all, validate_optional_checksum: true, library-default try_* options): exactly one
    # barcode per file. Checked through the C API against the vendored and the Homebrew libZXing 3.1.1 builds, also
    # with try_harder: false. bytes_hex is given where the bytes are not plain ASCII text (UTF-8, binary, GS1);
    # otherwise bytes == text.
    #
    # `format` is what zxing-cpp actually reports, which is not always the encoded variant: UPC-A and ISBN -> ean_13
    # (13-digit text), ITF-14 -> itf, standard Code 39 -> code_39, Compact PDF417 -> pdf417, Aztec Code/Rune -> aztec,
    # DataBar Stacked Omni -> databar_stacked, QR Model 2 -> qr_code.
    #
    # Readable formats without a fixture:
    #   qr_code_model_1  zint cannot encode QR Code Model 1
    #   other_barcode    generic ISO/IEC 15424 "X" symbology, no encoder (dx_film_edge is its only concrete variant)
    #   code_39_standard, itf_14, isbn, upc_a, aztec_code, aztec_rune, compact_pdf417, databar_stacked_omni,
    #   qr_code_model_2  never reported by the 3.1.1 readers (see above; upc_a only with formats excluding ean_13),
    #                    their encodings are covered by the fixtures below
    #   ean_5, ean_2     not readable on their own (no 'r' flag); covered as add-ons by ean_13_add_on_{2,5}
  YAML

  Fixture = Data.define(:name, :encoder, :transform, :render, :expect)

  # Builds every fixture and index.yml.
  class Generator
    def initialize
      @fixtures = []
      define_fixtures
    end

    def run
      check_tools!
      FileUtils.mkdir_p(OUT_DIR)
      entries = @fixtures.map { |fixture| build(fixture) }
      remove_stale_files
      write_index(entries)
      total = @fixtures.sum { |f| File.size(pgm_path(f.name)) }
      puts format("Wrote %d PGMs (%.1f KB) and %s", @fixtures.size, total / 1024.0, relative(INDEX))
    end

    private

    # --- fixture list -------------------------------------------------------------------------------------------

    def define_fixtures
      # QR Code (rqrcode unless noted)
      qr "qr_code", "Hello, World!", format: "qr_code", text: "Hello, World!"
      qr "qr_code_utf8", "Grüße, 世界", format: "qr_code", text: "Grüße, 世界", bytes: true,
        notes: "UTF-8 in byte mode without ECI; zxing-cpp guesses UTF-8 (has_eci false)"
      qr "qr_code_binary", BINARY, format: "qr_code", text: BINARY.bytes.pack("U*"), bytes: BINARY,
        content_type: "binary",
        notes: "byte mode, no ECI: text is the ISO-8859-1 reading of the bytes as UTF-8. ZXing_Barcode_text returns a " \
               "NUL-terminated C string, so a binding reading it with strlen gets only \"BIN\""
      qr "qr_code_inverted", "Inverted QR", transform: :invert, format: "qr_code", text: "Inverted QR",
        notes: "whole image inverted (white modules on black); expect inverted: true (needs try_invert, on by default)"
      qr "qr_code_mirrored", "Mirrored QR", transform: :mirror, format: "qr_code", text: "Mirrored QR",
        notes: "mirrored horizontally; expect mirrored: true"
      structured_append "qr_code_structured_append", ["Structured append 1/2;", "Structured append 2/2."]
      zint "micro_qr_code", "MICROQR", "Micro QR", MATRIX, format: "micro_qr_code", text: "Micro QR"
      zint "rmqr_code", "RMQR", "rMQR Code", MATRIX, format: "rmqr_code", text: "rMQR Code"

      # Data Matrix, Aztec, MaxiCode
      zint "data_matrix", "DATAMATRIX", "Data Matrix", [*MATRIX, "--square"], format: "data_matrix", text: "Data Matrix"
      zint "data_matrix_gs1", "DATAMATRIX", GS1_AIS, [*MATRIX, "--gs1", "--square"], format: "data_matrix",
        text: GS1_TEXT, bytes: true, content_type: "gs1", notes: "symbology identifier ]d2"
      zint "aztec", "AZTEC", "Aztec Code", MATRIX, format: "aztec", text: "Aztec Code",
        notes: "compact Aztec Code; zxing-cpp reports the family format aztec"
      zint "aztec_rune", "AZRUNE", "25", MATRIX, format: "aztec", text: "025",
        notes: "rune value 25 as three digits; reported as aztec (not aztec_rune), symbology identifier ]zC"
      zint "maxicode", "MAXICODE", "MaxiCode test 123", %w[--scale=0.5 --whitesp=4 --vwhitesp=4], format: "maxicode",
        text: "MaxiCode test 123",
        notes: "mode 4, ~5 px hexagons; zxing-cpp's MaxiCode reader only handles pure images (one symbol filling the image)"

      # PDF417 family
      zint "pdf417", "PDF417", "PDF417 symbol", LINEAR, format: "pdf417", text: "PDF417 symbol"
      zint "compact_pdf417", "PDF417COMP", "Compact PDF417", LINEAR, format: "pdf417", text: "Compact PDF417",
        notes: "zxing-cpp 3.1.1 reports compact PDF417 as pdf417"
      zint "micropdf417", "MICROPDF417", "MicroPDF417", LINEAR, format: "micropdf417", text: "MicroPDF417"

      # Code 128, Code 39 family, Code 93, Codabar
      zint "code_128", "CODE128", "Code 128", BARS, format: "code_128", text: "Code 128"
      zint "code_128_gs1", "GS1_128", GS1_AIS, BARS, format: "code_128", text: GS1_TEXT, bytes: true,
        content_type: "gs1", notes: "GS1-128, symbology identifier ]C1"
      zint "code_39", "CODE39", "CODE39", [*BARS, "--vers=1"], format: "code_39", text: "CODE39W",
        notes: "mod-43 check character W is valid and kept in the text (]A1)"
      zint "code_39_no_check", "CODE39", "CODE39", BARS, format: "code_39", text: "CODE39",
        read_options: {"validate_optional_checksum" => false},
        notes: "no check character. With validate_optional_checksum: true (gem default) the symbol is dropped, or " \
               "returned with a checksum error when return_errors: true"
      zint "code_39_extended", "EXCODE39", "Hello", [*BARS, "--vers=1"], format: "code_39_extended", text: "Hello3",
        notes: "full ASCII (\"H+E+L+L+O\"); the valid mod-43 check character 3 is kept after full-ASCII decoding (]A5)"
      zint "code_32", "CODE32", "14325678", BARS, format: "code_32", text: "A143256788",
        notes: "Italian pharmacode: \"A\" + 8 digits + check digit"
      zint "pharmazentralnummer", "PZN", "1234567", BARS, format: "pharmazentralnummer", text: "-12345678",
        notes: "PZN8: \"-\" + 7 digits + check digit, as encoded in Code 39"
      zint "code_93", "CODE93", "Code 93", BARS, format: "code_93", text: "Code 93",
        notes: "lowercase via full-ASCII shift characters; the two check characters are stripped"
      zint "codabar", "CODABAR", "A40156B", BARS, format: "codabar", text: "A40156B",
        notes: "start/stop characters A and B are part of the text"

      # ITF
      zint "itf", "C25INTER", "1234567895", BARS, format: "itf", text: "1234567895",
        notes: "last digit is a valid GTIN-style check digit (]I1)"
      zint "itf_no_check", "C25INTER", "1234567890", BARS, format: "itf", text: "1234567890",
        read_options: {"validate_optional_checksum" => false},
        notes: "invalid check digit (]I0). With validate_optional_checksum: true (gem default) the symbol is dropped, " \
               "or returned with a checksum error when return_errors: true"
      zint "itf_14", "ITF14", "1540014128876", BARS, transform: :margin, format: "itf", text: "15400141288763",
        notes: "ITF-14 with bearer bars; zxing-cpp 3.1.1 reports it as itf (]I1)"

      # EAN/UPC (zint computes the check digits)
      zint "ean_13", "EAN13", "400638133393", BARS, format: "ean_13", text: "4006381333931"
      zint "ean_13_add_on_2", "EAN13", "400638133393+12", ADDON_BARS, transform: :align_addon, format: "ean_13",
        text: "400638133393112", read_options: {"ean_add_on" => "read"},
        notes: "add-on digits are appended without separator (]E3); extra EanAddOn \"12\". Without ean_add_on: " \
               "read the text is \"4006381333931\""
      zint "ean_13_add_on_5", "EAN13", "400638133393+51234", ADDON_BARS, transform: :align_addon, format: "ean_13",
        text: "400638133393151234", read_options: {"ean_add_on" => "read"},
        notes: "add-on digits are appended without separator (]E3); extra EanAddOn \"51234\". Without ean_add_on: " \
               "read the text is \"4006381333931\""
      zint "ean_8", "EAN8", "9638507", BARS, format: "ean_8", text: "96385074", notes: "symbology identifier ]E4"
      zint "upc_a", "UPCA", "03600029145", BARS, format: "ean_13", text: "0036000291452",
        notes: "UPC-A is reported as ean_13 with a leading 0 (ISO/IEC 15420 ]E0 content); only with formats " \
               "excluding ean_13 (e.g. [:upc_a]) is it reported as upc_a, with the same 13-digit text"
      zint "upc_e", "UPCE", "0425261", BARS, format: "upc_e", text: "0042100005264",
        notes: "text is the 13-digit EAN form of the expanded UPC-A; extra UPCE holds the 8-digit form \"04252614\""
      zint "isbn", "ISBNX", "9780201379624", BARS, format: "ean_13", text: "9780201379624",
        notes: "ISBN (Bookland EAN-13) is reported as ean_13"

      # GS1 DataBar (content type GS1, symbology identifier ]e0)
      zint "databar_omni", "DBAR_OMN", GTIN, BARS, format: "databar_omni", text: GTIN_TEXT, bytes: true,
        content_type: "gs1"
      zint "databar_stacked", "DBAR_STK", GTIN, LINEAR, format: "databar_stacked", text: GTIN_TEXT, bytes: true,
        content_type: "gs1"
      zint "databar_stacked_omni", "DBAR_OMNSTK", GTIN, LINEAR, format: "databar_stacked", text: GTIN_TEXT,
        bytes: true, content_type: "gs1", notes: "zxing-cpp 3.1.1 reports DataBar Stacked Omni as databar_stacked"
      zint "databar_limited", "DBAR_LTD", GTIN, BARS, format: "databar_limited", text: GTIN_TEXT, bytes: true,
        content_type: "gs1"
      zint "databar_expanded", "DBAR_EXP", GS1_AIS, BARS, format: "databar_expanded", text: GS1_TEXT, bytes: true,
        content_type: "gs1"
      zint "databar_expanded_stacked", "DBAR_EXPSTK", GS1_AIS, LINEAR, format: "databar_expanded_stacked",
        text: GS1_TEXT, bytes: true, content_type: "gs1", notes: "3 rows of 2 segments"

      # Telepen, DX Film Edge
      zint "telepen_alpha", "TELEPEN", "Telepen", BARS, format: "telepen_alpha", text: "Telepen",
        notes: "symbology identifier ]B0"
      zint "telepen_numeric", "TELEPEN_NUM", "01234567", BARS, format: "telepen_numeric", text: "01234567",
        notes: "zint uses the full-ASCII start/stop pattern; zxing-cpp only guesses numeric (]B1) when a codeword " \
               "is < 32, i.e. a digit pair 00-04 (here 01) is present - other data decodes as telepen_alpha garbage"
      zint "dx_film_edge", "DXFILMEDGE", "112-1/10A", LINEAR, format: "dx_film_edge", text: "112-1/10A",
        notes: "DX number 112-1, frame 10A; symbology identifier ]XF"
    end

    def qr(name, payload, transform: nil, **expect)
      encoder = "rqrcode_core #{RQRCodeCore::VERSION} byte mode, EC level M, #{QR_MODULE_PX} px modules, " \
                "#{QR_QUIET_ZONE}-module quiet zone"
      encoder += ", #{TRANSFORMS.fetch(transform)}" if transform
      render = -> { apply(transform, *qr_raster(payload)) }
      @fixtures << Fixture.new(name:, encoder:, transform:, render:, expect:)
    end

    def zint(name, type, data, options, transform: nil, **expect)
      args = ["-b", type, *COMMON, *options, "-d", data]
      encoder = (["zint"] + args).map { |arg| shell_word(arg) }.join(" ")
      encoder += " (#{TRANSFORMS.fetch(transform)})" if transform
      render = -> { apply(transform, *zint_raster(args)) }
      @fixtures << Fixture.new(name:, encoder:, transform:, render:, expect:)
    end

    # QR Code structured append: one symbol per file. The ID is the QR parity byte (XOR of all message bytes), which
    # zxing-cpp reports as the decimal sequence id.
    def structured_append(prefix, parts)
      parity = parts.join.bytes.reduce(0, :^)
      parts.each_with_index do |part, index|
        zint "#{prefix}_#{index + 1}", "QRCODE", part, [*QR_ZINT, "--structapp=#{index + 1},#{parts.size},#{parity}"],
          format: "qr_code", text: part,
          sequence: {"index" => index, "size" => parts.size, "id" => parity.to_s},
          notes: "symbol #{index + 1} of #{parts.size}; the complete message is #{parts.join.inspect}"
      end
    end

    # --- rendering ----------------------------------------------------------------------------------------------

    def build(fixture)
      width, height, pixels = fixture.render.call
      validate!(fixture, width, height, pixels)
      File.binwrite(pgm_path(fixture.name), "P5\n#{width} #{height}\n255\n".b + pixels)
      entry(fixture)
    end

    # Module matrix -> 8-bit pixels, drawn directly (no zxing-cpp, no image library involved).
    def qr_raster(payload)
      modules = RQRCodeCore::QRCode.new(payload, level: :m, mode: :byte_8bit).modules
      size = (modules.size + 2 * QR_QUIET_ZONE) * QR_MODULE_PX
      margin = WHITE.chr * (QR_QUIET_ZONE * QR_MODULE_PX)
      quiet_rows = [WHITE.chr * size] * (QR_QUIET_ZONE * QR_MODULE_PX)
      rows = modules.flat_map do |row|
        line = margin + row.map { |dark| (dark ? BLACK : WHITE).chr * QR_MODULE_PX }.join + margin
        [line] * QR_MODULE_PX
      end
      [size, size, (quiet_rows + rows + quiet_rows).join]
    end

    def zint_raster(args)
      png = run!("zint", "--direct", "--filetype=PNG", *args)
      pgm = run!("magick", "png:-", "-colorspace", "Gray", "-depth", "8", "-strip", "pgm:-", stdin_data: png)
      header = pgm.match(/\AP5\s+(\d+)\s+(\d+)\s+255\s/n) or raise "unexpected magick output for #{args.inspect}"
      width, height = header.captures.map(&:to_i)
      [width, height, pgm.byteslice(header.end(0)..)]
    end

    def apply(transform, width, height, pixels)
      case transform
      when nil then [width, height, pixels]
      when :invert then [width, height, pixels.bytes.map { |v| WHITE - v }.pack("C*")]
      when :mirror then [width, height, rows(width, height, pixels).map(&:reverse).join]
      when :align_addon then align_addon(width, height, pixels)
      when :margin then margin(width, height, pixels)
      end
    end

    def margin(width, height, pixels)
      padded = width + 2 * MARGIN_PX
      side = WHITE.chr * MARGIN_PX
      quiet_rows = [WHITE.chr * padded] * MARGIN_PX
      lines = rows(width, height, pixels).map { |line| side + line + side }
      [padded, height + 2 * MARGIN_PX, (quiet_rows + lines + quiet_rows).join]
    end

    # zint draws EAN/UPC add-on bars lower than the main bars (it reserves room for the add-on text even with
    # --notext), so scan lines near the top cross the main symbol only and zxing-cpp would report it a second time
    # without the add-on. Drop those rows so that every scan line crosses both parts.
    def align_addon(width, height, pixels)
      lines = rows(width, height, pixels)
      last_bar = lines.filter_map { |line| line.rindex(BLACK.chr) }.max # right edge of the add-on
      first_black = lines.index { |line| line.include?(BLACK.chr) }
      addon_top = lines.index { |line| line.getbyte(last_bar) == BLACK }
      kept = lines[0...first_black] + lines[addon_top..]
      [width, kept.size, kept.join]
    end

    def rows(width, height, pixels)
      Array.new(height) { |y| pixels.byteslice(y * width, width) }
    end

    # Clean fixture: exact size, only black/white pixels, uniform background along all four edges.
    def validate!(fixture, width, height, pixels)
      name = fixture.name
      raise "#{name}: expected #{width * height} pixels, got #{pixels.bytesize}" unless pixels.bytesize == width * height
      raise "#{name}: not a bilevel image" unless pixels.delete(BILEVEL).empty?

      background = (fixture.transform == :invert) ? BLACK : WHITE
      lines = rows(width, height, pixels)
      edges = lines.first.bytes + lines.last.bytes + lines.flat_map { |line| [line.getbyte(0), line.getbyte(-1)] }
      raise "#{name}: quiet zone is not clean" unless edges.all?(background)
    end

    # --- index.yml ----------------------------------------------------------------------------------------------

    def entry(fixture)
      expect = fixture.expect
      format = expect.fetch(:format)
      bytes = (expect[:bytes] == true) ? expect.fetch(:text) : expect[:bytes]
      {
        "file" => "symbologies/#{fixture.name}.pgm",
        "format" => format,
        "symbology" => FAMILY.fetch(format),
        "text" => expect.fetch(:text),
        "bytes_hex" => bytes&.b&.unpack1("H*"),
        "content_type" => expect.fetch(:content_type, "text"),
        "encoder" => fixture.encoder,
        "read_options" => expect[:read_options],
        "sequence" => expect[:sequence],
        "notes" => expect.fetch(:notes, "")
      }.compact
    end

    def write_index(entries)
      encoders = "zint #{zint_version}, rqrcode_core #{RQRCodeCore::VERSION}"
      body = entries.map do |entry|
        entry.map.with_index { |(key, value), i| "#{i.zero? ? "- " : "  "}#{key}: #{yaml_value(value)}\n" }.join
      end
      yaml = format(HEADER, encoders:) + "\n" + body.join("\n")
      loaded = YAML.safe_load(yaml)
      raise "index.yml does not round-trip" unless loaded == entries

      File.write(INDEX, yaml)
    end

    PLAIN = /\A[a-z][a-z0-9_.\/]*\z/
    YAML_WORDS = %w[y n yes no on off true false null].freeze

    def yaml_value(value)
      case value
      when Hash then "{#{value.map { |k, v| "#{k}: #{yaml_value(v)}" }.join(", ")}}"
      when String then (value.match?(PLAIN) && !YAML_WORDS.include?(value)) ? value : yaml_quote(value)
      else value.to_s
      end
    end

    # YAML double-quoted scalar; control characters (C0, DEL, C1) as \xHH, everything else verbatim UTF-8.
    def yaml_quote(string)
      escaped = string.each_char.map do |char|
        code = char.ord
        if char == "\\" || char == "\""
          "\\#{char}"
        elsif code < 0x20 || (0x7F..0x9F).cover?(code)
          format("\\x%02X", code)
        else
          char
        end
      end
      "\"#{escaped.join}\""
    end

    # --- helpers ------------------------------------------------------------------------------------------------

    def check_tools!
      version = zint_version
      unless version && Gem::Version.new(version) >= MIN_ZINT
        abort "symbologies: zint >= #{MIN_ZINT} is required (found #{version || "none"}); e.g. `brew install zint`"
      end
      magick = run!("magick", "-version")
      abort "symbologies: ImageMagick 7 (`magick`) is required" unless magick.include?("ImageMagick 7")
    end

    def zint_version
      @zint_version ||= run!("zint", "--version")[/Zint version (\d+(?:\.\d+)+)/, 1]
    end

    # Runs a command (no shell) and returns its binary stdout; any failure or stderr output (zint prints warnings
    # there with exit status 0) aborts the generator.
    def run!(*argv, stdin_data: nil)
      out, err, status = Open3.capture3(*argv, stdin_data: stdin_data.to_s, binmode: true)
      return out if status.success? && err.empty?

      abort "symbologies: `#{argv.map { |a| shell_word(a) }.join(" ")}` failed: #{err.strip}"
    rescue Errno::ENOENT
      abort "symbologies: `#{argv.first}` not found on PATH (need zint >= #{MIN_ZINT} and ImageMagick 7)"
    end

    def shell_word(arg)
      arg.match?(%r{\A[\w.,:=/+@%-]+\z}) ? arg : "'#{arg.gsub("'", "'\\\\''")}'"
    end

    def remove_stale_files
      wanted = @fixtures.map { |f| pgm_path(f.name) }
      (Dir[File.join(OUT_DIR, "*.pgm")] - wanted).each { |path| File.delete(path) }
    end

    def pgm_path(name)
      File.join(OUT_DIR, "#{name}.pgm")
    end

    def relative(path)
      path.delete_prefix("#{ROOT}/")
    end
  end
end

SymbologyFixtures::Generator.new.run if $PROGRAM_NAME == __FILE__
